#ifndef ENGINECORE_APPLICATION_H
#define ENGINECORE_APPLICATION_H

enum APP_EXIT_CODE{
  APP_EXIT_SUCCESS = 0,
  APP_EXIT_CRITICAL,
};

enum APP_EXIT_CODE appstart(void);

#endif/*ENGINECORE_APPLICATION_H*/
