#ifndef ENGINECORE_GAME_WINDOW_INFO_H
#define ENGINECORE_GAME_WINDOW_INFO_H

#define MAP_WIDTH 19
#define MAP_HEIGHT 23

#define MAP_WIDTH_ASPECT 0.5f
#define MAP_HEIGHT_ASPECT 1
#define VERTICES_COUNT 4
#define INDICES_COUNT 6
#define TEX_SHIFT 1.0f

#define INVENTORY_TEX_LAYER 0.0f
#define INVENTORY_LAYER 1.0f
#define INVENTORY_TEXTURE_START_COORD 0.0f


#endif/*ENGINECORE_GAME_WINDOW_INFO_H*/
