#ifndef ENGINECORE_GAME_WINDOW_INFO_H
#define ENGINECORE_GAME_WINDOW_INFO_H

#define MAP_WIDTH_ASPECT 0.5f
#define MAP_HEIGHT_ASPECT 1
#define VERTICES_COUNT 4
#define INDICES_COUNT 6
#define TEX_SHIFT 1.0f

#endif/*ENGINECORE_GAME_WINDOW_INFO_H*/
