#ifndef ENGINECORE_TILES_INFO_H
#define ENGINECORE_TILES_INFO_H

#define TILE_SIZE 16
#define TILES_TYPE_NUMBER 4

enum TILE_TYPE{
  GROUND = 0,
  GRASS = 1,
  WALL = 2,
  TEST = 3,
};/*@TODO WHEN ADD SOME TILE --- INCREASE TILES_TYPE_NUMBER*/

#endif/*ENGINECORE_TILES_INFO_H*/
