#ifndef ENGINECORE_TILES_INFO_H
#define ENGINECORE_TILES_INFO_H

#define TILE_SIZE 16
#define TILES_TYPE_NUMBER 4

enum TILE_TYPE{
  ID_000000_ERROR = 0,
  ID_000001_GROUND = 1,
  ID_000002_GRASS = 2,
  ID_000003_WALL = 3,
};/*@TODO WHEN ADD SOME TILE --- INCREASE TILES_TYPE_NUMBER*/

#endif/*ENGINECORE_TILES_INFO_H*/
